apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hr-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mainakdas73/recruitment-project.git
    path: K8s
    targetRevision: hr-repo
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
